### ISSUE TITLE
Unable to generate mob

### ISSUE THREAD

**Issue by mimanglala** [CoreXDevelopment/NovaMobs#54]
1.1version
For example, zombie eggs can not be generated by clicking on the ground

**Comment by Asuna-Yuuki** [comment]
known issue

**Comment by PikyCZ** [comment]
Thanks for report..  you can use command /mob summon

**Comment by PetteriM1** [comment]
Command not work.

Unable to spawn.

**Comment by PetteriM1** [comment]
And no autospawn.

**Comment by PikyCZ** [comment]
@PetteriM1 We know about this bugs and missing features.. please stop spaming ..

**Comment by PetteriM1** [comment]
ok, sorry

**Comment by PikyCZ** [comment]
In version 1.1.5  spawn mobs is working ..
