### ISSUE TITLE
ReCreate Config and AutoSpawn

### ISSUE THREAD

**Issue by PikyCZ** [CoreXDevelopment/NovaMobs#55]
First: https://github.com/PikyCZ/MobPlugin/commit/38837a0ae8bbe549342b2d190114158f035229ef
- [x] Autospawn
- [x] Config

**Comment by PikyCZ** [comment]
https://github.com/PikyCZ/MobPlugin/tree/ReCreate

**Comment by PikyCZ** [comment]
WIP

**Comment by PikyCZ** [comment]
AutoSpawn is wokring .. Config is generated but without flags ..

**Comment by PikyCZ** [comment]
Config is generated with control flags and AutoSpawn is working

**Comment by lsw46** [comment]
It doesn't seem to have been updated

**Comment by PikyCZ** [comment]
Config a Autospawn is complete .. if yu need new version for nukkit 1.2 look at ReCreate Branch .. @lsw46
