### ISSUE TITLE
Can I ride a horse?

### ISSUE THREAD

**Issue by Shanwer** [CoreXDevelopment/NovaMobs#56]
I want to ride a horse.Please add this function.Thanks!My map is too big to reach anywhere on foot.

- [ ] Riding API
- [x] Riding Listener
- [x] Riding

**Comment by PikyCZ** [comment]
Another feature

**Comment by Asuna-Yuuki** [comment]
@PikyCZ  do you have discord?

**Comment by Asuna-Yuuki** [comment]
or somtin else

**Comment by PikyCZ** [comment]
Shanwer this feature is hard for me .. i can try create this feature but first is config a tasks.. i mean riding is not important.. riding is extra feature ..

**Comment by Asuna-Yuuki** [comment]
Hmm @PikyCZ  I know that PureEntitiesX has some cool things mey concert some cool tings

**Comment by PikyCZ** [comment]
PureEntitiesX not have riding .... but shear and others yeah ..

**Comment by PikyCZ** [comment]
- [ ] Riding
